# Generated by Django 4.1.2 on 2022-10-09 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('d', 'dastres'), ('s', 'sahafi'), ('a', 'amanat'), ('h', 'hazf')], default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
