# Generated by Django 4.1.2 on 2022-10-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('s', 'sahafi'), ('d', 'dastres'), ('h', 'hazf'), ('a', 'amanat')], max_length=150),
        ),
    ]
