# Generated by Django 4.1.2 on 2022-10-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('d', 'dastres'), ('h', 'hazf'), ('a', 'amanat'), ('s', 'sahafi')], max_length=150),
        ),
        migrations.AlterField(
            model_name='daste_bandi_ketab',
            name='Name',
            field=models.CharField(choices=[('f', 'فرهنگی'), ('s', 'سیاسی'), ('v', 'ورزشی'), ('a', 'اجتماعی')], max_length=150),
        ),
    ]
